export const HOME_FETCHING = "HOME_FETCHING";
export const HOME_SUCCESS = "HOME_SUCCESS";
export const HOME_FAILED = "HOME_FAILED";
export const HOME_BY_ID_SUCCESS = "HOME_BY_ID_SUCCESS";

export const KNOWLEDGE_FETCHING = "KNOWLEDGE_FETCHING";
export const KNOWLEDGE_SUCCESS = "KNOWLEDGE_SUCCESS";
export const KNOWLEDGE_FAILED = "KNOWLEDGE_FAILED";
export const KNOWLEDGE_BY_ID_SUCCESS = "KNOWLEDGE_BY_ID_SUCCESS";

export const APPLICATION_FETCHING = "APPLICATION_FETCHING";
export const APPLICATION_SUCCESS = "APPLICATION_SUCCESS";
export const APPLICATION_FAILED = "APPLICATION_FAILED";
export const APPLICATION_BY_ID_SUCCESS = "APPLICATION_BY_ID_SUCCESS";

export const CATEGORY_FETCHING = "CATEGORY_FETCHING";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILED = "CATEGORY_FAILED";
export const CATEGORY_BY_ID_SUCCESS = "CATEGORY_BY_ID_SUCCESS";

export const FILEATTACHMENT_FETCHING = "FILEATTACHMENT_FETCHING";
export const FILEATTACHMENT_SUCCESS = "FILEATTACHMENT_SUCCESS";
export const FILEATTACHMENT_FAILED = "FILEATTACHMENT_FAILED";
export const FILEATTACHMENT_BY_ID_SUCCESS = "FILEATTACHMENT_BY_ID_SUCCESS";

export const apiUrl = `${process.env.REACT_APP_API}/api`;
export const apiUrlimage = `${process.env.REACT_APP_API}`;
export const server = {
  HOME_URL: `Movies`,
  CATEGORY_URL: `Category`,
  APPLICATION_URL: `Application`,
  FILEATTACHMENT_URL: `FileAttachment`,
  KNOWLEDGE_URL: `KM`,
};
